name: tf-checks

on:
  pull_request:
  workflow_dispatch:

jobs:
  basic-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@v2
    with:
      working_directory: './_example/basic/'
      provider: none
  complete-example:
    uses: clouddrove/github-shared-workflows/.github/workflows/tf-checks.yml@v2
    with:
      working_directory: './_example/complete/'
      provider: none
